### 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # 사이킷런 - 전처리 모듈 -> 레이블인코더, 원핫인코더

### 데이터 불러오기

In [4]:
CSV_PATH = 'Clean_Dataset.csv'

df_origin = pd.read_csv(CSV_PATH)
df_origin.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [5]:
df_origin = df_origin.drop('Unnamed: 0', axis=1) # 컬럼 Unnamed: 0 삭제

df_origin.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

### 레이블 인코딩
- 범주형 데이터(문자열 데이터)에 숫자를 순서대로 매기는 방식
- 판다스와 사이킷런 모두 활용 가능

### pandas에서 레이블 인코딩 하기
- pd.factorize()

In [6]:
df = df_origin.copy() # 데이터프레임 복사
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  str
 1   flight            300153 non-null  str
 2   source_city       300153 non-null  str
 3   departure_time    300153 non-null  str
 4   stops             300153 non-null  str
 5   arrival_time      300153 non-null  str
 6   destination_city  300153 non-null  str
 7   class             300153 non-null  str
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(2), str(8)
memory usage: 25.2 MB

In [7]:
df['airline'].value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [9]:
pd.factorize(df['airline'])[0]

array([0, 0, 1, ..., 2, 2, 2], shape=(300153,))

In [10]:
df.shape

(300153, 11)

### .reshape(-1,1) 
- 1차원 배열을 (행 수, 1) 형태의 2차원으로 바꿔서 데이터프레임의 새 컬럼으로 대입하기 쉽게 한다.

In [11]:
pd.factorize(df['airline'])[0].reshape(-1,1) # 2차원

array([[0],
       [0],
       [1],
       ...,
       [2],
       [2],
       [2]], shape=(300153, 1))

In [12]:
df['label_encoding'] = pd.factorize(df['airline'])[0].reshape(-1,1)

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2

### 사이킷런으로 레이블 인코딩 하기 - LabelEncoder(알파벳 순서로)

### fit_transform()
- fit : 범주(문자열) 학습
- transform : 숫자 변환
- 학습하고 숫자 변환을 한번에 수행

In [14]:
le = LabelEncoder()
le.fit_transform(df['airline'])

array([4, 4, 0, ..., 5, 5, 5], shape=(300153,))

In [16]:
pd.set_option('display.max_columns', None) # 컬럼이 많아도 잘리지 않고 다 보이게 설정

In [17]:
df['airline_label_encoding'] = le.fit_transform(df['airline'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_label_encoding
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5

#### 레이블 인코딩 역변환(디코딩)하기

In [18]:
le.inverse_transform(df['airline_label_encoding'])

array(['SpiceJet', 'SpiceJet', 'AirAsia', ..., 'Vistara', 'Vistara',
       'Vistara'], shape=(300153,), dtype=object)

In [19]:
df['decoded'] = le.inverse_transform(df['airline_label_encoding'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_label_encoding,decoded
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4,SpiceJet
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4,SpiceJet
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0,AirAsia
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5,Vistara
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5,Vistara

### 원핫 인코딩
- 레이블 인코딩 시 문제점이 의도치 않게 숫자 크기 정보가 생겨서 이를 크기 순서로 오해할 경우가 있다.
- 이 문제를 해결하기 위해 원핫 인코딩이 등장
- 각 범주를 독립된 0 또는 1 컬럼으로 분리
- 범주 개수가 많아지면 컬럼 수가 급증하는 트레이드오프가 있다.
- 범주 개수가 적으면 원핫 인코딩을 추천, 많을 때는 신중히 판단을 한다.

### pandas 에서 원핫 인코딩하기 - pd.get_dummies()

In [20]:
df = df_origin.copy()

In [21]:
# class 컬럼을 원핫 인코딩
pd.get_dummies(df['class'])

        Business  Economy
0          False     True
1          False     True
2          False     True
3          False     True
4          False     True
...          ...      ...
300148      True    False
300149      True    False
300150      True    False
300151      True    False
300152      True    False

[300153 rows x 2 columns]

In [22]:
df[['Business','Economy']] = pd.get_dummies(df['class'])

In [23]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Business,Economy
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,False,True
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,False,True
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,False,True
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,False,True
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,False,True

### 사이킷런으로 원핫 인코딩하기 - OneHotEncoder 클래스

In [26]:
df = df_origin.copy()

oh = OneHotEncoder()

# fit_transform()에는 2차원 배열이 들어가야 한다.
oh.fit_transform(df['class'].values.reshape(-1,1)).toarray()

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], shape=(300153, 2))

OneHotEncoder 는 배열을 반환(array)
- 왜 바로 데이터프레임에 반영되지 않는가??
    - 머신러닝 파이프라인에 바로 연결해서 train/test data에 동일한 encoding 규칙을 일관되게 적용하기 위해
        설계된 도구이기 때문
    - 단순 EDA/전처리용으로는 get_dummies가 훨씬 간편하다.
    - 실제 머신러닝 모델링에서는 OneHotEncoder를 사용하는 경우도 많다.