In [18]:
import pandas as pd
import numpy as np

dust = pd.read_excel('dust1.xlsx')
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [19]:
# 문지열 형 변환
dust['측정일시'] = dust['측정일시'].astype(str)
dust['측정일시'] = dust['측정일시'].str.slice(0,8)

In [20]:
# 날짜형으로 변환
dust['측정일시'] = pd.to_datetime(dust['측정일시'])
dust['측정일시']

0    2021-04-01
1    2021-04-01
2    2021-04-01
3    2021-04-01
4    2021-04-01
5    2021-04-01
6    2021-04-01
7    2021-04-01
8    2021-04-01
9    2021-04-01
10   2021-04-01
11   2021-04-01
12   2021-04-01
13   2021-04-01
14   2021-04-01
15   2021-04-01
16   2021-04-01
17   2021-04-01
18   2021-04-01
19   2021-04-01
20   2021-04-01
21   2021-04-01
22   2021-04-01
23   2021-04-01
24   2021-04-02
25   2021-04-02
26   2021-04-02
27   2021-04-02
28   2021-04-02
29   2021-04-02
30   2021-04-02
31   2021-04-02
Name: 측정일시, dtype: datetime64[us]

## 날짜형을 년, 월, 일로 분리 추출

In [21]:
# dt 속성
dust['측정일시'].dt

In [22]:
dust['측정일시'].dt.year

0     2021
1     2021
2     2021
3     2021
4     2021
5     2021
6     2021
7     2021
8     2021
9     2021
10    2021
11    2021
12    2021
13    2021
14    2021
15    2021
16    2021
17    2021
18    2021
19    2021
20    2021
21    2021
22    2021
23    2021
24    2021
25    2021
26    2021
27    2021
28    2021
29    2021
30    2021
31    2021
Name: 측정일시, dtype: int32

## 년, 월, 일 컬럼 생성

In [23]:
dust['year'] = dust['측정일시'].dt.year # 연도 추출
dust['month'] = dust['측정일시'].dt.month # 월 추출
dust['day'] = dust['측정일시'].dt.day # 일 추출

In [24]:
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,year,month,day
0,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,2021,4,1
1,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,2021,4,1
2,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,2021,4,1
3,서울 송파구,도시대기,111273,송파구,2021-04-01,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,2021,4,1
4,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,2021,4,1

# 데이터 병합

In [25]:
s1 = pd.read_excel('nation.xlsx')
s2 = pd.read_excel('code.xlsx')

In [27]:
s1.head()

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486

In [28]:
s2.head()

  국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주

## pd.merge(데이터프레임1, 데이터프레임2, on=기준칼럼명, how='inner')

- how='inner' 'outer','left','right' 도 가능 (교집합, 차집합, 합집합 등)

In [30]:
# 국적코드 기준으로 merge
pd.merge(s1,s2,on='국적코드')

  국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [33]:
# 오른쪽 컬럼 기준 (차집합)
pd.merge(s1, s2, how='right', on='국적코드')

   국적코드   성별      입국객수      증가수  국적명
0   A01   남성  125000.0   8000.0  필리핀
1   A01   여성  130000.0  10000.0  필리핀
2   A02  NaN       NaN      NaN   일본
3   A03  NaN       NaN      NaN   미국
4   A04  NaN       NaN      NaN   중국
5   A05   남성     300.0     10.0   호주
6   A05   여성     200.0     50.0   호주
7   A06   남성  158912.0  24486.0  베트남
8   A06   여성  325000.0  63466.0  베트남
9   A07  NaN       NaN      NaN  스위스
10  A99  NaN       NaN      NaN   기타

# 데이터 그룹핑

## groupby()

In [35]:
# 국적코드 별 성별, 입국객수, 증가수
s1.groupby('국적코드').sum()

        성별    입국객수    증가수
국적코드
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [36]:
# 국적코드 별, 성별 별 ---> 입국객 수, 증가수
s1.groupby(['국적코드','성별']).sum()

           입국객수    증가수
국적코드 성별
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

In [8]:
# 221.p
import pandas as pd
covid = pd.read_csv('covid.csv', encoding='cp949')
covid.head()

       항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0

In [10]:
covid[covid['사례수']==covid['사례수'].max()]

     항목  사례수    증가   감소  변화없음
0  스마트폰  999  78.9  1.7  19.4

In [13]:
tmp = covid.sort_values(by='증가', ascending=False)
tmp[:3]

       항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6

In [14]:
# 222.p
vac = pd.read_csv('vaccine.csv')
vac.head()

         date  subject  day1num  day1sum  day1rate  day2num  day2sum  day2rate
0  2021.10.16  9505868    10673  7562283      79.6    66910  6191341      65.1
1  2021.10.15  9505868    14556  7551829      79.4   133580  6124432      64.4
2  2021.10.14  9505868     9609  7536654      79.3    94569  5989111      63.0
3  2021.10.13  9505868     9804  7526430      79.2    77503  5893191      62.0
4  2021.10.12  9505868    17274  7516070      79.1   110204  5814018      61.2

In [16]:
vac2 = vac.drop(['day1sum','day1rate','day2sum','day2rate'],axis=1)
vac2

           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [17]:
vac2.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [18]:
vac2.dtypes

date         str
subject    int64
day1num    int64
day2num    int64
dtype: object

In [20]:
vac2['date'] = pd.to_datetime(vac2['date'])
vac2['month'] = vac2['date'].dt.month
vac2.head()

        date  subject  day1num  day2num  month
0 2021-10-16  9505868    10673    66910     10
1 2021-10-15  9505868    14556   133580     10
2 2021-10-14  9505868     9609    94569     10
3 2021-10-13  9505868     9804    77503     10
4 2021-10-12  9505868    17274   110204     10

In [28]:
vac3 = vac2.drop(['date','subject'],axis=1)
vac3

     day1num  day2num  month
0      10673    66910     10
1      14556   133580     10
2       9609    94569     10
3       9804    77503     10
4      17274   110204     10
..       ...      ...    ...
174    23323     3411      4
175      200        0      4
176    10195      119      4
177    27074     2479      4
178    22501     2358      4

[179 rows x 3 columns]

In [29]:
vac3.groupby('month').mean()

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000

In [32]:
# 224.p
sig = pd.read_csv('signup.csv', encoding='cp949')
pro = pd.read_csv('professor.csv', encoding='cp949')

In [33]:
pd.merge(sig, pro, on='담당교수')

   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [40]:
pro.groupby('학과').count()

       담당교수
학과
인공지능      2
정보통신      1
컴퓨터공학     2