## 판다스 데이터 선택
## 열 선택하기

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('weather.csv')

In [5]:
df.temp

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

## 여러 컬럼 선택하기

In [7]:
df[['date','temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

## loc

- 데이터프레임명.loc[행, 열]
- 열번호는 생략 가능하나 행번호는 생략 불가

In [8]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [10]:
df.loc[0,['date','temp']]

date    2010-08-01
temp          28.7
Name: 0, dtype: object

In [12]:
df.loc[0] # 열은 생략 가능

date         2010-08-01
temp               28.7
max_wind            8.3
mean_wind           3.4
Name: 0, dtype: object

In [14]:
df.loc[:,'temp'] # :의 의미는 모든 행

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [ ]:
df.loc[:,['date','temp']] # 열 여러개 가져올 경우

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df.loc[0:5] # loc는 마지막 번호까지 포함한다. (range와 다름)

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6
5  2010-08-06  26.8       9.8        8.0

## iloc

- i는 정수 의미
- 데이터 프레임명.iloc[행번호, 열번호]
- 열번호는 생략 가능하나 행번호는 생략 불가

In [17]:
df.iloc[0,1]

np.float64(28.7)

In [ ]:
df.iloc[1:3] # 마지막 번호 포함 안함 (range와 같음)

         date  temp  max_wind  mean_wind
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [19]:
df.iloc[0,0:2]

date    2010-08-01
temp          28.7
Name: 0, dtype: object

In [20]:
df.iloc[1:3,0:3]

         date  temp  max_wind
1  2010-08-02  25.2       8.7
2  2010-08-03  22.1       6.3

## bool 인덱싱

In [30]:
w = df['temp']>=30
df[w] # True 만 추출

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6
1104  2013-08-09  30.6       9.9        6.4
1105  2013-08-10  30.6       7.4        3.8
2913  2018-07-23  30.5       6.5        1.6
2925  2018-08-04  30.3       5.8        3.0

### 조건에 맞는 데이터만 추출

In [36]:
# 최고로 더운 날
w = df['temp'] == df['temp'].max()
df[w]

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6

In [38]:
# 조건이 2개 이상
w = (df['temp']>=30) & (df['max_wind']>=9)
df[w]

            date  temp  max_wind  mean_wind
1104  2013-08-09  30.6       9.9        6.4

# 판다스 결측데이터 처리

## isna() --> 값이 nan(결측치)이라면 True

In [39]:
# 최대풍속이 측정되지 않은 모든 데이터 출력
df[df['max_wind'].isna()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

## 데이터프레임명.isnull().sum() --> 컬럼별 결측데이터 개수 확인

In [40]:
df.isnull().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [41]:
df.isnull().sum().sum() #전체 결측치 수

np.int64(10)

## 결측치 삭제하기 --> dropna()

In [ ]:
df.dropna() # 결측치를 제거한 상태를 확인만 하는 용도

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [48]:
df # 원본 데이터 유지되어 있다.

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [44]:
df2 = df.dropna()
df2

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [45]:
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

## 결측 데이터 대체하기 --> fillna(채울 값)

In [54]:
df['max_wind'].isnull().sum()
df3 = df

In [61]:
df3['max_wind'] = df3['max_wind'].fillna(0)
df3['max_wind'].isnull().sum()

np.int64(0)

In [56]:
avg = df3['max_wind'].mean()
avg

np.float64(7.911098931214031)

In [62]:
df3['max_wind'] = df3['max_wind'].fillna(avg)
df3['max_wind'].isnull().sum()

np.int64(0)

In [60]:
avg2 = df3['mean_wind'].mean()
df3['mean_wind'] = df3['mean_wind'].fillna(avg2)