## 판다스 데이터 가공하기

In [2]:
import pandas as pd
import numpy as np

filename = 'dust1.xlsx'

In [5]:
dust = pd.read_excel(filename)
dust.head(5)

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

## 컬럼(열, 변수, 피쳐) 삭제 / 생성

### drop(컬럼명, aixs=1)--> 컬럼(열) 삭제
- drop(행, aixs=0)--> 행 삭제 (aixs=0은 생략 가능)

In [9]:
# 지역, 망, 측정소코드 삭제
dust2 = dust.drop(['지역','망','측정소코드'], axis=1)
dust2.head(5)

  측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [8]:
dust.head(5)

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

### 컬럼 추가

- 데이터프레임명['추가하고싶은 컬럼 이름'] = 값

In [10]:
dust['city'] = '서울'

In [12]:
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,city
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

## 컬럼 이름 수정 --> rename()

- 데이터프레임명.rename(columns={'기존 이름':'새 이름'})

In [15]:
dust2 = dust.rename(columns={'측정소명':'name',
                     '측정일시':'date',
                     '주소':'addr'})

In [16]:
dust2.columns

Index(['지역', '망', '측정소코드', 'name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10',
       'PM25', 'addr', 'city'],
      dtype='str')

## 데이터 형 확인 --> dtypes

In [ ]:
dust.dtypes # 판다스 3버전부터 object -> str 변경

지역           str
망            str
측정소코드      int64
측정소명         str
측정일시       int64
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
city         str
dtype: object

## 데이터 형 변환 --> astype()

- 컬럼명.astype(바꿀 자료형)

In [18]:
dust2['date'].astype(str)

0     2021040101
1     2021040102
2     2021040103
3     2021040104
4     2021040105
5     2021040106
6     2021040107
7     2021040108
8     2021040109
9     2021040110
10    2021040111
11    2021040112
12    2021040113
13    2021040114
14    2021040115
15    2021040116
16    2021040117
17    2021040118
18    2021040119
19    2021040120
20    2021040121
21    2021040122
22    2021040123
23    2021040124
24    2021040201
25    2021040202
26    2021040203
27    2021040204
28    2021040205
29    2021040206
30    2021040207
31    2021040208
Name: date, dtype: str

In [19]:
dust2['date'] = dust2['date'].astype(str)

In [20]:
dust2.dtypes

지역           str
망            str
측정소코드      int64
name         str
date         str
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
addr         str
city         str
dtype: object

In [21]:
dust2['date']

0     2021040101
1     2021040102
2     2021040103
3     2021040104
4     2021040105
5     2021040106
6     2021040107
7     2021040108
8     2021040109
9     2021040110
10    2021040111
11    2021040112
12    2021040113
13    2021040114
14    2021040115
15    2021040116
16    2021040117
17    2021040118
18    2021040119
19    2021040120
20    2021040121
21    2021040122
22    2021040123
23    2021040124
24    2021040201
25    2021040202
26    2021040203
27    2021040204
28    2021040205
29    2021040206
30    2021040207
31    2021040208
Name: date, dtype: str

In [22]:
# 첫 8자리만 자른다 --> slice
dust2['date'] = dust2['date'].str.slice(0,8)

# 시간 날짜 형식으로 바꾸기 --> to_datetime()

In [ ]:
dust2['date'] = pd.to_datetime(dust2['date'])
dust2['date']

In [28]:
dust2.dtypes

지역                  str
망                   str
측정소코드             int64
name                str
date     datetime64[us]
SO2             float64
CO              float64
O3              float64
NO2             float64
PM10              int64
PM25              int64
addr                str
city                str
dtype: object